version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: payment_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3310:3306" # Avoid conflict with local mysql if any
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: payment_redis
    ports:
      - "6380:6379"  # 로컬 Redis(6379)와 충돌 방지
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
